// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.sportit.sportitfinal;

import ch.unige.idsi.sportit.sportitfinal.Chemins;

import java.util.ArrayList;

import com.google.maps.model.LatLng;

privileged aspect Chemins_Roo_JavaBean {
    

	public ArrayList<LatLng> Chemins.getChemin() {
        return this.chemin;
    }
    
    public void Chemins.setChemin(ArrayList<LatLng> chemin) {
        this.chemin = chemin;
    }
    
}
