// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.sportit.sportitfinal;

import ch.unige.idsi.sportit.sportitfinal.Chemins;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Chemins_Roo_Jpa_Entity {
    
    declare @type: Chemins: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Chemins.id;
    
    @Version
    @Column(name = "version")
    private Integer Chemins.version;
    
    public Long Chemins.getId() {
        return this.id;
    }
    
    public void Chemins.setId(Long id) {
        this.id = id;
    }
    
    public Integer Chemins.getVersion() {
        return this.version;
    }
    
    public void Chemins.setVersion(Integer version) {
        this.version = version;
    }
    
}
