// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.sportit.sportitfinal;

import ch.unige.idsi.sportit.sportitfinal.Chemins;
import ch.unige.idsi.sportit.sportitfinal.CheminsController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect CheminsController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String CheminsController.create(@Valid Chemins chemins, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, chemins);
            return "cheminses/create";
        }
        uiModel.asMap().clear();
        chemins.persist();
        return "redirect:/cheminses/" + encodeUrlPathSegment(chemins.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String CheminsController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Chemins());
        return "cheminses/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String CheminsController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("chemins", Chemins.findChemins(id));
        uiModel.addAttribute("itemId", id);
        return "cheminses/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String CheminsController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("cheminses", Chemins.findCheminsEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) Chemins.countCheminses() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("cheminses", Chemins.findAllCheminses(sortFieldName, sortOrder));
        }
        return "cheminses/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String CheminsController.update(@Valid Chemins chemins, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, chemins);
            return "cheminses/update";
        }
        uiModel.asMap().clear();
        chemins.merge();
        return "redirect:/cheminses/" + encodeUrlPathSegment(chemins.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String CheminsController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Chemins.findChemins(id));
        return "cheminses/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String CheminsController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Chemins chemins = Chemins.findChemins(id);
        chemins.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/cheminses";
    }
    
    void CheminsController.populateEditForm(Model uiModel, Chemins chemins) {
        uiModel.addAttribute("chemins", chemins);
    }
    
    String CheminsController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
