// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.sportit.sportitfinal;

import ch.unige.idsi.sportit.sportitfinal.Chemins;
import java.util.List;

privileged aspect Chemins_Roo_JavaBean {
    
    public List<Double> Chemins.getLatitude() {
        return this.latitude;
    }
    
    public void Chemins.setLatitude(List<Double> latitude) {
        this.latitude = latitude;
    }
    
    public List<Double> Chemins.getLongitude() {
        return this.longitude;
    }
    
    public void Chemins.setLongitude(List<Double> longitude) {
        this.longitude = longitude;
    }
    
}
