// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.sportit.sportitfinal;

import ch.unige.idsi.sportit.sportitfinal.Chemins;
import java.util.ArrayList;

privileged aspect Chemins_Roo_JavaBean {
    
    public ArrayList<ArrayList<Double>> Chemins.getPoints() {
        return this.points;
    }
    
    public void Chemins.setPoints(ArrayList<ArrayList<Double>> points) {
        this.points = points;
    }
    
}
