// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.sportit.sportitfinal;

import ch.unige.idsi.sportit.sportitfinal.Infrastructures;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Infrastructures_Roo_Configurable {
    
    declare @type: Infrastructures: @Configurable;
    
}
