// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.sportit.roo;

import ch.unige.idsi.sportit.roo.Chemin;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Chemin_Roo_Configurable {
    
    declare @type: Chemin: @Configurable;
    
}
