// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.sportit.roo;

import ch.unige.idsi.sportit.roo.Chemin;
import ch.unige.idsi.sportit.roo.CheminController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect CheminController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String CheminController.create(@Valid Chemin chemin, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, chemin);
            return "chemins/create";
        }
        uiModel.asMap().clear();
        chemin.persist();
        return "redirect:/chemins/" + encodeUrlPathSegment(chemin.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String CheminController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Chemin());
        return "chemins/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String CheminController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("chemin", Chemin.findChemin(id));
        uiModel.addAttribute("itemId", id);
        return "chemins/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String CheminController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("chemins", Chemin.findCheminEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) Chemin.countChemins() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("chemins", Chemin.findAllChemins(sortFieldName, sortOrder));
        }
        return "chemins/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String CheminController.update(@Valid Chemin chemin, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, chemin);
            return "chemins/update";
        }
        uiModel.asMap().clear();
        chemin.merge();
        return "redirect:/chemins/" + encodeUrlPathSegment(chemin.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String CheminController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Chemin.findChemin(id));
        return "chemins/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String CheminController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Chemin chemin = Chemin.findChemin(id);
        chemin.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/chemins";
    }
    
    void CheminController.populateEditForm(Model uiModel, Chemin chemin) {
        uiModel.addAttribute("chemin", chemin);
    }
    
    String CheminController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
