// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.sportit.roo;

import ch.unige.idsi.sportit.roo.Chemin;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Chemin_Roo_Jpa_Entity {
    
    declare @type: Chemin: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Chemin.id;
    
    @Version
    @Column(name = "version")
    private Integer Chemin.version;
    
    public Long Chemin.getId() {
        return this.id;
    }
    
    public void Chemin.setId(Long id) {
        this.id = id;
    }
    
    public Integer Chemin.getVersion() {
        return this.version;
    }
    
    public void Chemin.setVersion(Integer version) {
        this.version = version;
    }
    
}
